In [1]:
print("Hello")

Hello


In [2]:
import numpy

In [3]:
import numpy as np

In [8]:
myList = [10, 12, 14]

In [5]:
print(np.__version__)

1.14.3


In [6]:
import pandas as pd

In [7]:
print(pd.__version__)

0.23.0


In [9]:
myArray = np.array(myList)

In [10]:
myArray

array([10, 12, 14])

In [11]:
myArrayFloat = np.array(myList, dtype='float')

In [13]:
myArrayFloat

array([10., 12., 14.])

In [15]:
myArrayRange = np.arange(start=20, stop=30)

In [16]:
myArrayRange

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
myArrayRange = np.arange(20, 30, 1)

In [19]:
myArrayNan  = np.array([1, 3, 4, np.nan, 23, 56, np.nan, 23])

In [20]:
myArrayNan.sum()

nan

In [22]:
np.nansum(myArrayNan)

87.0

In [23]:
myTwoDArray = np.array([(1, 2, 3, 4),(6, 7, 2, 7)])

In [24]:
myTwoDArray

array([[1, 2, 3, 4],
       [6, 7, 2, 7]])

In [25]:
myTwoDArray = np.array([[1, 2, 3, 4],[6, 7, 2, 7]])

In [26]:
myTwoDArray

array([[1, 2, 3, 4],
       [6, 7, 2, 7]])

In [28]:
import sys

In [35]:
sys.getsizeof(5)

28

In [30]:
print(sys.getsizeof(5) * len(myList))

84


In [31]:
len(myList)

3

In [45]:
sys.getsizeof(15)

28

In [37]:
print(myArray.size * myArray.itemsize)

12


In [38]:
myArray.size

3

In [39]:
myArray.itemsize

4

In [44]:
myArray

array([10, 12, 14])

In [46]:
sys.getsizeof(5)

28

In [47]:
sys.getsizeof(15)

28

In [48]:
sys.getsizeof('15')

51

In [49]:
sys.getsizeof(15.0)

24

In [50]:
sys.getsizeof(15.12)

24

In [51]:
sys.getsizeof("jwjf")

53

In [52]:
import numpy as np
import time

SIZE=1000000
list1=range(SIZE)
list2=range(SIZE)


array1=np.arange(SIZE)
array2=np.arange(SIZE)


start=time.time()

result=[(x+y) for x,y in zip(list1,list2)]

print("Python list took:",(time.time()-start)*1000)
#==========================================================
start=time.time()

result=array1+array2

print("Python Array took:",(time.time()-start)*1000)

Python list took: 119.99988555908203
Python Array took: 18.000125885009766


In [53]:
myTwoDArray.ndim

2

In [54]:
myArray.ndim

1

In [55]:
myArray.dtype

dtype('int32')

In [56]:
myArray.shape

(3,)

In [57]:
myTwoDArray.size

8

In [59]:
myTwoDArray.shape

(2, 4)

In [60]:
myTwoDArray.reshape(4,2)

array([[1, 2],
       [3, 4],
       [6, 7],
       [2, 7]])

In [66]:
myTwoDArray.max()

7

In [67]:
myTwoDArray.ravel()

array([1, 2, 3, 4, 6, 7, 2, 7])

In [68]:
myTwoDArray.min()

1

In [69]:
myTwoDArray.sum()

32

In [72]:
myTwoDArray.sum(1)#0 is column 1 is row

array([10, 22])

In [71]:
myTwoDArray.sum(axis=0)

array([ 7,  9,  5, 11])

In [75]:
np.sqrt(myTwoDArray)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.44948974, 2.64575131, 1.41421356, 2.64575131]])

In [77]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
myTwoDArray1 = myTwoDArray

In [80]:
np.vstack((myTwoDArray, myTwoDArray1))

array([[1, 2, 3, 4],
       [6, 7, 2, 7],
       [1, 2, 3, 4],
       [6, 7, 2, 7]])

In [81]:
np.hstack((myTwoDArray, myTwoDArray1))

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [6, 7, 2, 7, 6, 7, 2, 7]])

In [83]:
np.hsplit(np.hstack((myTwoDArray, myTwoDArray1)), 2)

[array([[1, 2, 3, 4],
        [6, 7, 2, 7]]), array([[1, 2, 3, 4],
        [6, 7, 2, 7]])]

In [84]:
np.vsplit(np.vstack((myTwoDArray, myTwoDArray1)), 2)

[array([[1, 2, 3, 4],
        [6, 7, 2, 7]]), array([[1, 2, 3, 4],
        [6, 7, 2, 7]])]

In [87]:
array=np.arange(30).reshape(2,15)
print(array)

a=np.hsplit(array,3)
print(a[0])
print(a[1])
print(a[2])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [86]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
